name = "mac-login-worker"
main = "worker.js"
compatibility_date = "2024-06-01"
assets = { directory = "./mac-homepage", binding = "ASSETS", html_handling = "drop-trailing-slash", not_found_handling = "404-page" }
routes = [
    { pattern = "mac-netzwerk.net", custom_domain = true }
]

[vars]
DISCORD_CALLBACK_URL = "https://mac-netzwerk.net/login/callback"
WEBSITE_URL = "https://mac-netzwerk.net"

[[d1_databases]]
binding = "DB"
database_name = "mac-db"
database_id = "b7b88538-a490-4afc-8eda-01ca73573ddb"

