name: Deploy to VPS

on:
  push:
    branches: [ main ]  # oder master, je nach Ihrem Standard-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no sinnreich@mac-netzwerk.net << 'EOF'
          cd /var/www/
          git pull origin main
        EOF
