name: Deploy to VPS

on:
  push:
    branches: [ main ]  # oder master, je nach Ihrem Standard-Branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Website
      uses: actions/checkout@v4
    
    - name: Deploy to MAC-Netzwerk VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: mac-netzwerk.net
        username: sinnreich
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Deploying MAC-Netzwerk Website..."
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S -v
          
          # Ins Website-Verzeichnis (Apache DocumentRoot)
          cd /var/www/html/MAC-Website
          
          # Website aktualisieren
          git pull
          pm2 restart MAC-Backend --update-env
          
          # Korrekte Dateirechte für Apache setzen
          find . -type f -name "*.html" -exec chmod 644 {} \;
          find . -type f -name "*.css" -exec chmod 644 {} \;
          find . -type f -name "*.js" -exec chmod 644 {} \;
          find . -type f -name "*.png" -exec chmod 644 {} \;
          find . -type f -name "*.jpg" -exec chmod 644 {} \;
          find . -type f -name "*.svg" -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          
          echo "MAC-Netzwerk Website deployed!"
          echo "Live unter: https://mac-netzwerk.net"
